### ISSUE TITLE
The UnitTest check shouldn't be run on the production app

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/NSObject-HYPTesting#4]
When I run app in production I don't want the code to run "Is it UnitTest target" all the time.
The solution would be co create a separate subclass for DATAStack, that would override those methods and do them in sync way.

Moved from https://github.com/NSElvis/DATAStack/issues/13

**Comment by 3lvis** [comment]
@kostiakoval So you're saying that in production apps `[NSObject isUnitTesting]` always returns YES?

**Comment by kostiakoval** [comment]
nope, the idea is that I don't want to run `[NSObject isUnitTesting]` every time I run `performInBackground` code. I would like to run  `[NSObject isUnitTesting]` only once

**Comment by 3lvis** [comment]
@kostiakoval why do you need that?

**Comment by 3lvis** [comment]
@kostiakoval I thought it was a bug, why do we need to change?

**Comment by kostiakoval** [comment]
this is not an issue of that Pod, I think it improvement suggestion of DATAStack

**Comment by 3lvis** [comment]
ok, moving back!
